### ISSUE TITLE
Apache access conf is overwritten by old syntax

### ISSUE THREAD

**Issue by QGuLL** [AlternC/alternc-certbot#10]
I've a alternc that had several upgrade and i've tried to install alternc-certbot from the actual jessie + alternc-nightly.

Installed version :
alternc                       3.3.11~zznightly201710130201
alternc-certbot               0.0.10

The .well-known/acme-challenge path gives 403 forbidden error, due to the default configuration applied on / : deny from all in alternc.conf, mod_access_compat is enabled, and in this configuration, the old syntax has priority, so that the `Require all granted` in alternc-certbot.conf is ignored : 

```
 <IfModule mod_authz_core.c>
     Require all granted
 </IfModule>
 <IfModule !mod_authz_core.c>
     Order allow,deny
     Allow from all
     Satisfy Any
 </IfModule>
```

I've manage to doge the problem with the actual patch : 
```
-    <IfModule !mod_authz_core.c>
+   <IfModule mod_access_compat.c>
```

Maybe shouldn't I have access_compat enabled ?

**Comment by camlafit** [comment]
Hello

As test was on fresh install, mod_compat was not enabled.
I'll add a new test to enable old config is this module is enabled.

**Comment by camlafit** [comment]
Hello

Can you try nightly version and confirm it's ok ?

thanks

**Comment by QGuLL** [comment]
Didn't tried the nightly but installed manually the new .conf, and it was good.
