### ISSUE TITLE
Champ manquant dans la version des packages alternc-certbot

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/alternc-certbot#14]
Les versions récentes d'alternc-certbot à partir de bintray ne marche pas lors de l'installation: erreur dans la chaîne du champ « Version » : « 0.0.12- »: revision number is empty

Le problème est d'ailleurs plus répandu en regardant la liste des packages ici: https://dl.bintray.com/alternc/nightly/pool/main/a/alternc/

**Comment by camlafit** [comment]
Salut

Normalement cela n’empêche pas l'installation des paquets "stable" dans quel cas rencontres tu le problème.
On peut probablement améliorer le makefile en conséquence
