### ISSUE TITLE
Rendre les packages debian disponible à partir de dépôt alternC

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/alternc-certbot#15]
Serait-il possible de rendre les packages disponible dans le dépôt d'AlternC? Ça évitera à ce que le monde dois ajouter deux sources externes à leur installation.

**Comment by camlafit** [comment]
Hello

Prévu mais le système de packaging et de maintenance ne permet par pas pour le moment le faire.

Pour le moment aucun délai à court terme pour résoudre ce problème, en raison d'un problème de disponibilité humaine :/
