### ISSUE TITLE
Remove debian/files

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/alternc-certbot#24]
Hi,

I was trying to make debian source packages from this repo and dpkg-genchanges failed with the message

`
 ../alternc-certificate-provider-letsencrypt_0.0.15_amd64.buildinfo: No such file or directory
`

In the end I traced the source of the issue to the debian/files file which is committed in the repository.  According to https://www.debian.org/doc/debian-policy/#generated-files-list-debian-files this file should not be kept in the source (it's meant to be temporary) and as a pre-caution the clean target should remove it.

Thanks,
Kienan

**Comment by kienanstewart** [comment]
See PR #25

**Comment by camlafit** [comment]
merged
