### ISSUE TITLE
Ne pas écraser apache.pem en cas de problème

### ISSUE THREAD

**Issue by GrosQuicKFR** [AlternC/alternc-certbot#3]
Le script /usr/lib/alternc/install.d/alternc-certbot
Écrase apache.pem sans crier gare.

Il faudrait vérifier la présence et la cohérence de "/etc/letsencrypt/live/$FQDN/privkey.pem" et  "/etc/letsencrypt/live/$FQDN/fullchain.pem" avant.

Car en cas de problème, le apache.pem est écrasé, et ensuite plus de certification possible puisque apache2 refusera la transaction avec letsencrypt.

**Comment by camlafit** [comment]
I must check how to do this with preserve update process. 
Actually same script is used to create first certificate and renew it then during renew apache.pem is yet present.

**Comment by camlafit** [comment]
should be solve in 0.0.3 version
