### ISSUE TITLE
alternc-certbot.conf pas à la bonne place

### ISSUE THREAD

**Issue by kent1D** [AlternC/alternc-certbot#4]
Sur les distribs récentes, /etc/apache2/conf.d/alternc-certbot.conf devrait être /etc/apache2/conf-available/alternc-certbot.conf suivi d'un `a2enconf alternc-certbot.conf`

/etc/apache2/conf.d/* n'est pas forcément chargé

**Comment by camlafit** [comment]
Salut

L'objectif est de fournir un seul paquet qui fonctionne tant pour jessie que wheezy.

Avec wheezy a2enconf n'existe pas. Je vais voir comment faire pour permettre le bon comportement avec jessie et +.

A noter que de mon coté les test en jessie et wheezy fonctionne bien avec la 0.0.5. Est ce que tu as un cas qui coince ?

**Comment by kent1D** [comment]
Là je suis en stable donc stretch en fait.

**Comment by camlafit** [comment]
ok
Je vais regarder mais commet actuellement alternc ne valide pas jessie, stretch est un peu optimiste :)
Dans tous les cas faut traiter ce problème

**Comment by kent1D** [comment]
Pour info(pour mon usage) ça marche bien sur stretch sauf des bricoles que je remonte rapidement. La diff jessie / stretch semble pas énorme

**Comment by camlafit** [comment]
Salut

Ok c'est noté :) l'objectif premier c'est jessie car la future stable pour
alternc .... Mais si on peut avoir la vraie stable autant en profiter.
Merci pour tes retours et n'hésite pas à continuer.

**Comment by camlafit** [comment]
Nightly 0.0.5-xx should be solve this problem, can you test and confirm.
Then I'll release 0.0.6 in stable 

thanks

**Comment by kent1D** [comment]
Seems perfect

**Comment by camlafit** [comment]
Thanks 0.0.6 is released
