### ISSUE TITLE
Request only system certificates during alternc.install

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/alternc-certbot#43]
Hi,

when alternc.install is run the alternc-cerbot script will request certificates (new or renewals) for all sub-domains. In cases where there are many domains installed this takes a very long time and it would be nice to avoid doing that.

I propose requesting only system certificates when alternc.install is run, but requesting all certificates (user and system) during the alternc-cerbot cron runs.

Would this be okay with y'all?

**Comment by camlafit** [comment]
Hello

I understand the problem but i'm not convinced.
Alternc-install has to purpose to provide a full running instance. Following this logic we must provide all ssl service at this time.

Maybe an asyn script to or force cron to run subitly after

**Comment by kienanstewart** [comment]
I'm not opposed to starting a cron run after the alternc.install, but I'm not sure I see the need when it will run a few times a day any way.

I think that requesting only system certificates is sufficient to provide a running instance. In the case of any given install it will provide certificates for dovecot/postfix, the alternc bureau url, ftp, etc.  The only difference here is that user certificates won't be immediately requested.

The time taken to run alternc.install should be fairly minimal since it's the way configuration changes are "supposed" to be deployed. If I need to deploy new configuration on a server with 100+ or 1000+ domains I _really don't_ want to wait such a long time.

**Comment by camlafit** [comment]
Hello

Then should be an option. 
After an upgrade , I _want_ to manage certificates on all existing domains hostid. When script is ran, I can continue to work on panel part updating ssl configuration. I _don't want to wait_ an another cup of day/hours to manage them.

We do yet that with fixperms, which could be very looooong also.

**Comment by kienanstewart** [comment]
Yup, I'm down to make it an option

**Comment by camlafit** [comment]
nice, wait you PR :)

**Comment by kienanstewart** [comment]
PR #50
