### ISSUE TITLE
erreur lors de la création des certifs pour autoconfig et autodiscover

### ISSUE THREAD

**Issue by quenenni** [AlternC/alternc-certbot#51]
Pour revenir sur le premier point du ticket #48, j'ai trouvé le problème.

Les requêtes GET sur les autoconfig et autodiscover sont toutes bloquées car une requête sur le sous-dossier .well-known/acme-challenge ne correspond à aucun des patterns des règles Rewriterule définies dans les vhost des autoconfig et autodiscover.

```
  RewriteEngine On
  # Mail autoconfig
  RewriteRule ^/mail/mailautoconfig.xml$ /mailautoconfig_thunderbird.php [L]
  RewriteRule ^/mail/config-v1.1.xml$ /mailautoconfig_thunderbird.php [L]
  RewriteRule ^mail/mailautoconfig.xml$ /mailautoconfig_thunderbird.php [L]
  RewriteRule ^mail/config-v1.1.xml$ /mailautoconfig_thunderbird.php [L]
  RewriteRule ^/autodiscover/autodiscover.xml$ /mailautoconfig_outlook.php [L]
  RewriteRule ^/Autodiscover/Autodiscover.xml$ /mailautoconfig_outlook.php [L]
  RewriteRule ^/Autodiscover.xml$ mailautoconfig_outlook.php [L]
  RewriteRule ^/autodiscover.xml$ mailautoconfig_outlook.php [L]
  RewriteRule ^autodiscover/autodiscover.xml$ /mailautoconfig_outlook.php [L]
  RewriteRule ^Autodiscover/Autodiscover.xml$ /mailautoconfig_outlook.php [L]
  RewriteRule ^Autodiscover.xml$ mailautoconfig_outlook.php [L]
  RewriteRule ^autodiscover.xml$ mailautoconfig_outlook.php [L]
  RewriteRule (.*) - [F]
```

Dans ce cas, on arrive sur la règle "RewriteRule (.*) - [F]" qui bloque la requête.

L'alias /well-known/acme-challenge/ n'est pas utilisé car les règles RewriteRule sont traitées avant les définitions d'alias.

Je n'ai pas réussi à retrouver la doc officiel d'Apache qui spécifie ça, mais un commentaire ici le dit aussi (commentaire tout en bas):
https://serverfault.com/questions/372115/apache2-how-to-exclude-alias-from-rewrite-rules

Si on met la dernière ligne en commentaire, ça fonctionne.

**Comment by quenenni** [comment]
https://httpd.apache.org/docs/2.4/fr/rewrite/vhosts.html#simple.rewrite
`
Comme mod_rewrite s'exécute avant tout autre module de traduction d'URI (comme mod_alias), il faut lui ordonner explicitement d'ignorer toute URL susceptible d'être traitée par ces autres modules. Et comme ces règles auraient sinon court-circuité toute directive ScriptAlias, nous devons faire en sorte que mod_rewrite déclare explicitement ces correspondances.
`

**Comment by quenenni** [comment]
En ajoutant la règle
 ```
RewriteCond %{REQUEST_FILENAME} !/.well-known/acme-challenge/
```
ça fonctionne

**Comment by camlafit** [comment]
Solve by https://github.com/AlternC/AlternC/commit/d1d410ed657115def398acdbaf51551d9257f04b
