### ISSUE TITLE
AlternC certbot can't process certificates for domains which end up with the -NNNN suffix

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/alternc-certbot#56]
Certbot may, in certain cases, generate folders for certificates like `/etc/letsencrypt/live/example.tld-0001`, in cases where a domain's CSR has been deleted. The certificate provider is unable to process/import certificates from those.

**Comment by camlafit** [comment]
Hello

related to #61
certbot has any consistency and break some behavior. Use an another acme script should be resolve this issue.
