### ISSUE TITLE
Respecter les quotas?

### ISSUE THREAD

**Issue by kent1D** [AlternC/alternc-certbot#6]
Du coup est ce qu'il ne faudrait pas faire tomber les quotas, en tout cas ton plugin ne prend pas du tout en compte les quotas

**Comment by camlafit** [comment]
C'est à dire ?
Idéalement il faudrait limiter le nombre de certificats à la limite imposée par l'administration + le nombre exact de certificats généré par let's encrypt.

Pour le moment est impossible car alternc-ssl ne fournit qu'un seul type de quota.

**Comment by kent1D** [comment]
Disons que dans l'interface cela rend le truc peu glorieux avec des comptes qui prennent en compte les certificats letsencrypt "Certificats SSL (30/20)" par exemple

**Comment by camlafit** [comment]
Salut

J'ai bien compris mais du fait du fonctionnement de alternc-ssl je n'ai pas
de solution élégante à proposer dans l'immédiat.
Mais on va bien trouver un truc.

**Comment by kent1D** [comment]
Tu sais un ticket peut rester ouvert un peu ;)

**Comment by camlafit** [comment]
Salut

Suite au devcamp d'octobre 2017, je pense qu'on peut clore ce ticket. En pratique alternc-ssl détourne la notion du quota en valeur booléenne. C'est en fait 0 (pas de certficats) ou plus de 1 (gestion des certificats autorisée).

C'est dans ce cas un problème propre à https://github.com/AlternC/alternc et sa gestion des quota.

A noter que alternc-ssl va être (futur plus ou moins proche) intégré dans le core d'AlternC.  Le ssl n'est plus en 2018 une option.  
Il serait peut être plus pertinent d'ouvrir un ticket dans la partie AlternC qui est concernée par cette gestion/fonctionnalité de quota.
